name: CI/CD Curso NodeJS Matias Castro

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci && cp .env.example .env
      - name: Run test
        env:
            DB_URI_TEST: ${{ secrets.DB_URI_TEST }}
            SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        run: npm test && echo ::set-output name=things::$(grep "FAIL" test-output.log | wc -l)
        id: counter
        shell: bash 
      - name: Revisar test
        if:  steps.counter.outputs.things != '0'
        run: exit 1
  deploy:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v2 
      - name: Deploy in EC2
        env:
            PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
            HOSTNAME : ${{ secrets.HOST_DNS }}
            USER_NAME : ${{ secrets.USERNAME }}
            
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 400 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
          
            #Now we have got the access of EC2 and we will start the deploy .
            cd /home/ubuntu/API_REST_NODEJS &&
            sudo su &&
            sudo rm -rf node_modules &&
            sudo git checkout master &&
            sudo git fetch --all &&
            sudo git reset --hard origin/master &&
            sudo git pull origin master &&
            sudo npm i && sudo npm run start:prod
          '